---

- name: Ensure OpenSSl and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages


- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - git
    - python-dev
    - python-pip
    - python-pycurl
    - ipython
    - supervisor
  tags: packages


- name: Install newrelic
  pip: name=newrelic
  tags: packages


# Note that we're specifying the version number here as we don't want to use
# the latest version. The latest version of virtualenv is using a newer version
# of pip which doesn't work work with some of the packages we use in Django.
- name: Install virtualenv
  pip: name=virtualenv version=1.10.1
  tags: packages