---

- name: Ensure that an hourly Twitter auto-follow job exists
  cron: name="hourly twitter auto-follow"
        special_time=hourly
        user={{ gunicorn_user }}
        job="bash {{ project_path }}/scripts/run_twitter_auto_follow.sh"
        state=present
  when: setup_cron_jobs
  tags: cron

- name: Ensure that an hourly db backup job exists
  cron: name="hourly db backup"
        special_time=hourly
        user={{ gunicorn_user }}
        job="bash {{ project_path }}/scripts/run_backup.sh hourly"
        state=present
  when: setup_cron_jobs
  tags: cron

- name: Ensure that a daily db backup job exists
  cron: name="daily db backup"
        special_time=daily
        user={{ gunicorn_user }}
        job="bash {{ project_path }}/scripts/run_backup.sh daily"
        state=present
  when: setup_cron_jobs
  tags: cron
